-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(SALES) AS SALES
FROM (
SELECT P.PRODUCT_CODE, P.PRICE * S.SALES_AMOUNT AS SALES
FROM PRODUCT P, OFFLINE_SALE S
WHERE P.PRODUCT_ID = S.PRODUCT_ID
)
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC
