-- 코드를 입력하세요
-- SELECT *
-- FROM
-- (SELECT O.ANIMAL_ID, O.NAME
-- FROM ANIMAL_INS O LEFT JOIN ANIMAL_OUTS O
-- ON I.ANIMAL_ID = O.ANIMAL_ID
-- ORDER BY O.DATETIME
-- FETCH FIRST 2 ROWS ONLY)


SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O  JOIN ANIMAL_INS I
ON I.ANIMAL_ID = O.ANIMAL_ID 
ORDER BY O.DATETIME - I.DATETIME DESC
FETCH FIRST 2 ROWS ONLY