-- 코드를 입력하세요
SELECT S.YEAR, S.MONTH, U.GENDER, COUNT(DISTINCT S.USER_ID) AS USERS
FROM USER_INFO U, (
SELECT ONLINE_SALE_ID, USER_ID, PRODUCT_ID, SALES_AMOUNT, TO_CHAR(SALES_DATE, 'YYYY') AS YEAR,
TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH
FROM ONLINE_SALE
) S
WHERE U.USER_ID = S.USER_ID AND GENDER IS NOT NULL
GROUP BY S.YEAR, S.MONTH, U.GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC


