-- -- 코드를 입력하세요
-- 2021에 가입하고 구매한 이력 있는사람

SELECT TO_CHAR(S.SALES_DATE, 'YYYY') AS YEAR, TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) AS MONTH, COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS, ROUND((COUNT(DISTINCT U.USER_ID) / (SELECT COUNT(*) AS TOTAL
FROM USER_INFO
WHERE TO_CHAR(JOINED, 'YYYY') = '2021')),1) AS PUCHASED_RATIO
FROM USER_INFO U,  ONLINE_SALE  S
WHERE U.USER_ID = S.USER_ID AND TO_CHAR(U.JOINED, 'YYYY') = '2021'
GROUP BY TO_CHAR(S.SALES_DATE, 'YYYY'), TO_CHAR(S.SALES_DATE, 'MM')
ORDER BY YEAR ASC, MONTH ASC



-- 2021 전체 회원가입 
-- (SELECT COUNT(*) AS TOTAL
-- FROM USER_INFO
-- WHERE TO_CHAR(JOINED, 'YYYY') = '2021')