-- 코드를 입력하세요
-- 두개 조인 해서 더해 그리고 정렬해서 상위 3개

SELECT F.FLAVOR
FROM FIRST_HALF F, JULY J
WHERE F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
FETCH FIRST 3 ROWS ONLY
