-- 코드를 입력하세요
SELECT TO_NUMBER(T.HOUR) AS HOUR , COUNT(A.HOUR) AS COUNT
FROM (
SELECT ANIMAL_ID, ANIMAL_TYPE, NAME,SEX_UPON_OUTCOME, TO_CHAR(DATETIME,'HH24') AS HOUR
FROM ANIMAL_OUTS) A RIGHT JOIN ( SELECT LEVEL-1 AS HOUR
    FROM DUAL 
    CONNECT BY LEVEL<=24) T
    ON A.HOUR = T.HOUR
GROUP BY TO_NUMBER(T.HOUR)
ORDER BY HOUR