-- 코드를 입력하세요

SELECT T.HOUR, COUNT(TO_CHAR(O.DATETIME,'HH24')) AS COUNT
FROM ANIMAL_OUTS O RIGHT JOIN (SELECT LEVEL - 1 AS HOUR
FROM DUAL
CONNECT BY LEVEL <= 24) T
ON TO_CHAR(O.DATETIME, 'HH24') = T.HOUR
GROUP BY (T.HOUR)
ORDER BY HOUR
