-- 코드를 입력하세요
SELECT P.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM (
SELECT MEMBER_ID, COUNT(*) AS CNT
FROM REST_REVIEW  
GROUP BY MEMBER_ID
ORDER BY CNT DESC
FETCH FIRST 1 ROW ONLY) T, MEMBER_PROFILE P, REST_REVIEW R
WHERE T.MEMBER_ID = P.MEMBER_ID AND T.MEMBER_ID = R.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
