-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
WHERE I.ITEM_ID IN(
SELECT T.ITEM_ID
FROM ITEM_TREE AS T 
JOIN ITEM_INFO AS I ON T.PARENT_ITEM_ID=I.ITEM_ID
WHERE I.RARITY LIKE 'RARE'
)
ORDER BY ITEM_ID DESC;

