-- 코드를 입력하세요
SELECT '/home/grep/src/'||F.BOARD_ID||'/'||F.FILE_ID||F.FILE_NAME||F.FILE_EXT AS FILE_PATH
FROM USED_GOODS_FILE F, 
(
SELECT BOARD_ID
FROM USED_GOODS_BOARD  
ORDER BY VIEWS DESC
FETCH FIRST 1 ROWS ONLY) B
WHERE B.BOARD_ID = F.BOARD_ID 
ORDER BY FILE_ID DESC
