-- 코드를 입력하세요
-- 카테고리로 묶어서 가장 비싼거 찾기 찾고 비교 해서 출력?
SELECT CATEGORY,PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (PRICE, CATEGORY) IN  (
SELECT MAX(PRICE) AS PRICE , CATEGORY
FROM FOOD_PRODUCT
GROUP BY CATEGORY
HAVING CATEGORY IN ('과자', '국', '김치','식용유'))
ORDER BY MAX_PRICE DESC
